[package]
name = "wasmship"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "wasmship"
path = "src/wasmship/lib.rs"

[[bin]]
name = "wasmship"
test = false
doc = false

[dependencies]
